<a href="https://colab.research.google.com/github/LK920/tesorflow/blob/master/SmartCar_load_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd

from keras.models import load_model
from keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#파이썬 버전
import sys
sys.version

'3.6.9 (default, Jul 17 2020, 12:50:27) \n[GCC 8.4.0]'

In [ ]:
#구글 드라이브 연동
from google.colab import drive
drive.mount('/content/drive')

In [2]:
#데이터셋 로드
df = pd.read_csv('/content/drive/My Drive/Tensorflow_works/data/CarDrivingIncidentInfo_Test.csv')
df

    wea  temp  hum  arrCar  ...  innCond  carSpd  steeAng  acciPos
0     0     1    0       1  ...        0       0        1        0
1     0     0    0       1  ...        0       1        0        0
2     0     0    0       0  ...        1       0        0        0
3     1     0    1       1  ...        1       2        0        2
4     1     0    2       0  ...        2       1        0        0
5     2     1    0       1  ...        2       2        0        1
6     0     0    0       0  ...        2       1        0        0
7     0     0    0       0  ...        1       1        0        0
8     2     0    0       1  ...        2       1        0        2
9     0     0    2       1  ...        0       0        0        0
10    1     2    1       1  ...        2       2        1        2
11    2     1    0       1  ...        1       2        2        2
12    1     0    1       0  ...        0       1        0        0
13    0     0    1       0  ...        2       2        1        1
14    0     1    1       1  ...        0       0        0        0
15    0     0    0       0  ...        1       2        0        0
16    2     0    1       1  ...        1       0        1        0
17    1     0    1       0  ...        0       2        1        0
18    1     0    2       1  ...        1       2        0        1
19    0     2    0       0  ...        2       1        0        0
20    0     1    2       0  ...        1       2        0        1
21    1     0    0       1  ...        2       2        0        1
22    1     0    1       0  ...        0       2        0        0
23    1     1    1       1  ...        0       2        0        1
24    0     1    1       1  ...        1       1        0        1
25    0     0    2       0  ...        2       2        0        1
26    1     0    0       2  ...        0       1        0        0
27    1     0    2       1  ...        2       0        0        1
28    0     0    1       1  ...        0       1        2        1
29    0     0    0       1  ...        2       1        0        0

[30 rows x 11 columns]

In [3]:
#데이터 전처리
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

Y_train = to_categorical(Y_train)
Y_test = to_categorical(Y_test)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [4]:
model = load_model('/content/drive/My Drive/Tensorflow_works/smartcar_model')
model

In [5]:
result = model.evaluate(X_train, Y_train)
result

1/1 [==============================] - 0s 2ms/step - loss: 0.5730 - acc: 0.9583

[0.5729875564575195, 0.9583333134651184]